version: '3.8'

services:

    mongo:
          image: mongo
          container_name: mongo
          ports:
                - 27017:27017
          restart: always
          hostname: host-mongo
          environment:
                 MONGO_INITDB_ROOT_USERNAME: admin
                 MONGO_INITDB_ROOT_PASSWORD: password
          volumes:
                - ./mongo-data:/data/db


    mongo-express:

            image: mongo-express
            container_name: mongo-express
            ports:
                - 8081:8081
            restart: always
            environment:
                 ME_CONFIG_MONGODB_ADMINUSERNAME: admin
                 ME_CONFIG_MONGODB_ADMINPASSWORD: password
                 ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/

